const base = {
  'code[class*="language-"]': {
    fontFamily: "var(--font-mono)",
    fontSize: "1em",
    lineHeight: "1.6",
    textAlign: "left",
    whiteSpace: "pre",
    wordSpacing: "normal",
    wordBreak: "normal",
    wordWrap: "normal",
    tabSize: 2,
    hyphens: "none",
  },
  'pre[class*="language-"]': {
    fontFamily: "var(--font-mono)",
    fontSize: "1em",
    lineHeight: "1.6",
    textAlign: "left",
    whiteSpace: "pre",
    wordSpacing: "normal",
    wordBreak: "normal",
    wordWrap: "normal",
    tabSize: 2,
    hyphens: "none",
    margin: 0,
    overflow: "auto",
  },
  'code[class*="language-"]::selection': { background: "rgba(255, 180, 84, 0.22)" },
  'pre[class*="language-"]::selection': { background: "rgba(255, 180, 84, 0.22)" },
} as const;

export const ayuDarkSyntaxTheme = {
  ...base,
  'code[class*="language-"]': {
    ...base['code[class*="language-"]'],
    color: "#e6e1cf",
    background: "#0d1017",
  },
  'pre[class*="language-"]': {
    ...base['pre[class*="language-"]'],
    color: "#e6e1cf",
    background: "#0d1017",
  },
  comment: { color: "#5c6773", fontStyle: "italic" },
  prolog: { color: "#5c6773" },
  doctype: { color: "#5c6773" },
  cdata: { color: "#5c6773" },
  punctuation: { color: "#b3b1ad" },
  property: { color: "#ffb454" },
  tag: { color: "#5ccfe6" },
  boolean: { color: "#ff8f40" },
  number: { color: "#ff8f40" },
  constant: { color: "#ff8f40" },
  symbol: { color: "#ff8f40" },
  selector: { color: "#bae67e" },
  "attr-name": { color: "#ffd173" },
  string: { color: "#bae67e" },
  char: { color: "#bae67e" },
  builtin: { color: "#bae67e" },
  inserted: { color: "#bae67e" },
  operator: { color: "#f29e74" },
  entity: { color: "#f29e74" },
  url: { color: "#95e6cb" },
  variable: { color: "#e6e1cf" },
  atrule: { color: "#ffd173" },
  "attr-value": { color: "#bae67e" },
  keyword: { color: "#ffa0a0" },
  function: { color: "#ffd173" },
  "class-name": { color: "#73d0ff" },
  regex: { color: "#95e6cb" },
  important: { color: "#ff8f40", fontWeight: "600" },
  deleted: { color: "#ff8f8f" },
} as const;

export const ayuLightSyntaxTheme = {
  ...base,
  'code[class*="language-"]': {
    ...base['code[class*="language-"]'],
    color: "#4f5867",
    background: "#f8f9fb",
  },
  'pre[class*="language-"]': {
    ...base['pre[class*="language-"]'],
    color: "#4f5867",
    background: "#f8f9fb",
  },
  comment: { color: "#abb0b6", fontStyle: "italic" },
  prolog: { color: "#abb0b6" },
  doctype: { color: "#abb0b6" },
  cdata: { color: "#abb0b6" },
  punctuation: { color: "#697386" },
  property: { color: "#ff8f40" },
  tag: { color: "#399ee6" },
  boolean: { color: "#f07171" },
  number: { color: "#f07171" },
  constant: { color: "#f07171" },
  symbol: { color: "#f07171" },
  selector: { color: "#86b300" },
  "attr-name": { color: "#e6a23c" },
  string: { color: "#86b300" },
  char: { color: "#86b300" },
  builtin: { color: "#86b300" },
  inserted: { color: "#75a743" },
  operator: { color: "#ed9366" },
  entity: { color: "#ed9366" },
  url: { color: "#4cbf99" },
  variable: { color: "#4f5867" },
  atrule: { color: "#e6a23c" },
  "attr-value": { color: "#75a743" },
  keyword: { color: "#fa8d3e" },
  function: { color: "#f2ae49" },
  "class-name": { color: "#399ee6" },
  regex: { color: "#4cbf99" },
  important: { color: "#ff8f40", fontWeight: "600" },
  deleted: { color: "#d95757" },
} as const;
